title: lightLess-dev-blog
description: This where our developers talk about updates and their work in lightLess-dev

remote_theme: jekyll/minima
minima:
  skin: auto
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

social_links:
    - { platform: github,         user_url: "https://github.com/lightless-dev" }
