title: lightLess-dev-blog
description: This where our developers talk about updates and insight on their contibutions to lightLess-dev
author: lightless-dev
  name: lightless-dev

remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  social_links: 
    - { icon: "github", title: "Us on github", url: "https://github.com/lightless-dev" }
  show-excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

favicon: https://lightless-dev.github.io/Blog/favicon.png

baseurl: /Blog
